export type Vibe =
  | 'saas'
  | 'portfolio'
  | 'restaurant'
  | 'agency'
  | 'blog'
  | 'event'
  | 'ecommerce'
  | 'coffee'
  | 'minimal';

export function inferVibe(prompt: string): Vibe {
  const p = prompt.toLowerCase();
  if (/(saas|startup|software)/.test(p)) return 'saas';
  if (/(portfolio|designer|photograph)/.test(p)) return 'portfolio';
  if (/(restaurant|bistro|food|cafe)/.test(p)) return 'restaurant';
  if (/(agency|studio|consult)/.test(p)) return 'agency';
  if (/(blog|writer|magazine)/.test(p)) return 'blog';
  if (/(event|conference|meetup)/.test(p)) return 'event';
  if (/(shop|store|e-?commerce|product)/.test(p)) return 'ecommerce';
  if (/(coffee|café)/.test(p)) return 'coffee';
  return 'minimal';
}

export function generateHtmlFromPrompt(prompt: string): string {
  const vibe = inferVibe(prompt);
  return buildHtml(vibe, prompt);
}

function htmlEscape(text: string): string {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function buildHtml(vibe: Vibe, prompt: string): string {
  const safePrompt = htmlEscape(prompt || '');
  const font = 'Inter';
  const head = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Generated by VibeCode" />
  <title>VibeCode — ${safePrompt || 'Instant site'}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=${font}:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <script src="https://cdn.tailwindcss.com"></script>
  <script>tailwind.config={theme:{extend:{fontFamily:{sans:['${font}', 'ui-sans-serif','system-ui']}}}}</script>
  <style>body{font-family:'${font}',system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif}</style>
</head>`;

  const sections: Record<Vibe, string> = {
    saas: saasSections(safePrompt),
    portfolio: portfolioSections(safePrompt),
    restaurant: restaurantSections(safePrompt),
    agency: agencySections(safePrompt),
    blog: blogSections(safePrompt),
    event: eventSections(safePrompt),
    ecommerce: ecommerceSections(safePrompt),
    coffee: coffeeSections(safePrompt),
    minimal: minimalSections(safePrompt)
  };

  const body = sections[vibe];
  return `${head}
<body class="bg-neutral-950 text-neutral-100">
${siteHeader()}
${body}
${siteFooter()}
</body>
</html>`;
}

function siteHeader(): string {
  return `
<header class="sticky top-0 z-40 w-full border-b border-white/10 bg-neutral-950/70 backdrop-blur">
  <div class="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
    <div class="flex items-center gap-2">
      <div class="h-6 w-6 rounded bg-gradient-to-tr from-indigo-500 to-sky-400"></div>
      <span class="text-sm font-medium tracking-tight">VibeCode</span>
    </div>
    <nav class="hidden gap-6 text-sm text-neutral-300 md:flex">
      <a class="hover:text-white" href="#features">Features</a>
      <a class="hover:text-white" href="#sections">Sections</a>
      <a class="hover:text-white" href="#contact">Contact</a>
    </nav>
    <a href="#contact" class="rounded-md bg-white/10 px-3 py-1.5 text-sm hover:bg-white/15">Get started</a>
  </div>
</header>`;
}

function siteFooter(): string {
  return `
<footer class="border-t border-white/10 py-10">
  <div class="mx-auto max-w-6xl px-4 text-center text-sm text-neutral-400">
    Built with <span class="text-white">VibeCode</span>. Customize this code as you like.
  </div>
  <script>
    // Basic smooth scroll for internal links
    document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.querySelector(a.getAttribute('href')).scrollIntoView({behavior:'smooth'});}));
  </script>
</footer>`;
}

function heroBase({ title, subtitle, cta }: { title: string; subtitle: string; cta: string }): string {
  return `
<section class="relative isolate overflow-hidden bg-gradient-to-b from-indigo-600/20 to-transparent">
  <div class="mx-auto max-w-6xl px-4 py-20">
    <div class="max-w-3xl">
      <h1 class="text-4xl font-semibold tracking-tight sm:text-5xl">${title}</h1>
      <p class="mt-4 text-lg text-neutral-300">${subtitle}</p>
      <div class="mt-6 flex gap-3">
        <a href="#contact" class="rounded-md bg-indigo-500 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-400">${cta}</a>
        <a href="#features" class="rounded-md border border-white/15 px-4 py-2 text-sm hover:bg-white/5">Learn more</a>
      </div>
    </div>
  </div>
</section>`;
}

function featuresBase(items: Array<{ title: string; desc: string }>): string {
  const grid = items
    .map(
      (it) => `
    <div class="rounded-lg border border-white/10 bg-white/5 p-5">
      <h3 class="text-base font-medium">${it.title}</h3>
      <p class="mt-1.5 text-sm text-neutral-300">${it.desc}</p>
    </div>`
    )
    .join('\n');
  return `
<section id="features" class="py-14">
  <div class="mx-auto max-w-6xl px-4">
    <div class="mb-8 flex items-end justify-between">
      <h2 class="text-2xl font-semibold tracking-tight">Features</h2>
      <a href="#" class="text-sm text-indigo-400 hover:text-indigo-300">Explore</a>
    </div>
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
      ${grid}
    </div>
  </div>
  </section>`;
}

function testimonialsSection(): string {
  return `
<section class="py-14">
  <div class="mx-auto max-w-6xl px-4">
    <div class="rounded-xl border border-white/10 bg-gradient-to-br from-white/5 to-transparent p-8">
      <p class="text-lg">“This site was vibed into existence in minutes. Unreal.”</p>
      <p class="mt-2 text-sm text-neutral-400">— Happy Human</p>
    </div>
  </div>
</section>`;
}

function ctaSection(): string {
  return `
<section id="contact" class="py-16">
  <div class="mx-auto max-w-6xl px-4">
    <div class="flex flex-col items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/5 p-8 sm:flex-row">
      <div>
        <h3 class="text-xl font-medium">Start your project</h3>
        <p class="text-sm text-neutral-300">Tell us what you want to build and we will reach out.</p>
      </div>
      <form class="flex w-full max-w-md gap-2">
        <input type="email" placeholder="you@example.com" class="flex-1 rounded-md border border-white/15 bg-black/40 px-3 py-2 text-sm outline-none placeholder:text-neutral-500" />
        <button class="rounded-md bg-indigo-500 px-4 py-2 text-sm font-medium hover:bg-indigo-400">Send</button>
      </form>
    </div>
  </div>
</section>`;
}

function saasSections(p: string): string {
  return `
${heroBase({
  title: 'Build faster with a modern toolkit',
  subtitle: p || 'A sleek SaaS landing with gradients and confidence.',
  cta: 'Start free'
})}
${featuresBase([
  { title: 'No setup', desc: 'Generate, edit, and deploy — all in the browser.' },
  { title: 'Responsive', desc: 'Every section ships mobile-first by default.' },
  { title: 'Components', desc: 'Composable blocks you can rearrange freely.' }
])}
${testimonialsSection()}
${ctaSection()}`;
}

function portfolioSections(p: string): string {
  return `
${heroBase({
  title: 'Show your best work with taste',
  subtitle: p || 'A playful portfolio with pastel accents and a clean grid.',
  cta: 'Hire me'
})}
<section id="sections" class="py-14">
  <div class="mx-auto max-w-6xl px-4">
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
      ${Array.from({ length: 6 })
        .map(
          (_, i) => `<div class="aspect-[4/3] rounded-lg bg-gradient-to-br from-pink-500/20 to-purple-500/10 ring-1 ring-white/10"></div>`
        )
        .join('')}
    </div>
  </div>
</section>
${ctaSection()}`;
}

function restaurantSections(p: string): string {
  return `
${heroBase({
  title: 'Crafted flavors, cozy atmosphere',
  subtitle: p || 'A warm restaurant landing with a seasonal menu highlight.',
  cta: 'Reserve a table'
})}
<section id="sections" class="py-14">
  <div class="mx-auto max-w-6xl px-4">
    <div class="grid gap-4 sm:grid-cols-2">
      <div class="rounded-lg border border-white/10 bg-white/5 p-6">
        <h3 class="text-lg font-medium">Seasonal Menu</h3>
        <ul class="mt-3 space-y-2 text-sm text-neutral-300">
          <li>Heirloom Tomato Salad</li>
          <li>Wild Mushroom Risotto</li>
          <li>Lemon Thyme Roast Chicken</li>
        </ul>
      </div>
      <div class="rounded-lg border border-white/10 bg-white/5 p-6">
        <h3 class="text-lg font-medium">Hours & Location</h3>
        <p class="mt-3 text-sm text-neutral-300">123 Market Street — 5pm to 10pm</p>
      </div>
    </div>
  </div>
  </section>
${ctaSection()}`;
}

function agencySections(p: string): string {
  return `
${heroBase({
  title: 'We design experiences that convert',
  subtitle: p || 'An agency site with case studies and credibility.',
  cta: 'Contact us'
})}
${featuresBase([
  { title: 'Strategy', desc: 'Research-led discovery to map outcomes.' },
  { title: 'Design', desc: 'Tasteful interfaces that feel effortless.' },
  { title: 'Build', desc: 'Production-grade web engineering.' }
])}
${ctaSection()}`;
}

function blogSections(p: string): string {
  return `
${heroBase({
  title: 'Thoughts, notes, and explorations',
  subtitle: p || 'A minimal blog with readable typography.',
  cta: 'Subscribe'
})}
<section id="sections" class="py-14">
  <div class="mx-auto max-w-3xl px-4">
    <article class="prose prose-invert max-w-none">
      <h2>Why fast iteration wins</h2>
      <p>Short feedback loops help ideas compound. Shipping small and often keeps momentum.</p>
      <h3>Principles</h3>
      <ul><li>Start simple</li><li>Gather signal</li><li>Refine</li></ul>
    </article>
  </div>
</section>
${ctaSection()}`;
}

function eventSections(p: string): string {
  return `
${heroBase({
  title: 'The Future Web Summit',
  subtitle: p || 'A single-day event on web tooling and creative coding.',
  cta: 'Get tickets'
})}
${featuresBase([
  { title: 'Speakers', desc: 'World-class builders and artists.' },
  { title: 'Workshops', desc: 'Hands-on sessions to level up.' },
  { title: 'Venue', desc: 'In the heart of the city.' }
])}
${ctaSection()}`;
}

function ecommerceSections(p: string): string {
  return `
${heroBase({
  title: 'Simple products, delightful details',
  subtitle: p || 'A clean storefront with featured products grid.',
  cta: 'Shop now'
})}
<section id="sections" class="py-14">
  <div class="mx-auto max-w-6xl px-4">
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
      ${Array.from({ length: 6 })
        .map(
          (_, i) => `<div class="rounded-lg border border-white/10 bg-white/5 p-4">
            <div class="aspect-square rounded-md bg-gradient-to-br from-indigo-500/20 to-sky-500/10 ring-1 ring-white/10"></div>
            <div class="mt-3 flex items-center justify-between text-sm">
              <span>Product ${i + 1}</span>
              <span class="text-neutral-300">$${(i + 1) * 9}</span>
            </div>
            <button class="mt-2 w-full rounded-md bg-white/10 py-1.5 text-sm hover:bg-white/15">Add to cart</button>
          </div>`
        )
        .join('')}
    </div>
  </div>
</section>
${ctaSection()}`;
}

function coffeeSections(p: string): string {
  return `
${heroBase({
  title: 'Brewed with care',
  subtitle: p || 'A cozy coffee shop vibe with warm tones and beans.',
  cta: 'Visit us'
})}
${featuresBase([
  { title: 'Single Origin', desc: 'We source from small farms we know.' },
  { title: 'Roasted Weekly', desc: 'Fresh profiles, balanced flavor.' },
  { title: 'Community', desc: 'A place to read, write, and connect.' }
])}
${ctaSection()}`;
}

function minimalSections(p: string): string {
  return `
${heroBase({
  title: 'Clean, minimal, and fast',
  subtitle: p || 'Start simple and iterate as you go.',
  cta: 'Get started'
})}
${featuresBase([
  { title: 'Accessible', desc: 'High contrast, keyboard friendly.' },
  { title: 'Typographic', desc: 'Readable layouts and spacing.' },
  { title: 'Composable', desc: 'Add or remove sections freely.' }
])}
${ctaSection()}`;
}


